EstateInvestmentWebApplication/Models/DatabaseEntitiesModel/New.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EstateInvestmentWebApplication.Models.DatabaseEntitiesModel
{
    public class New
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Bắt buộc nhập trường này")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Bắt buộc nhập trường này")]
        [MaxLength(500, ErrorMessage = "Không được quá 500 ký tự")]
        public string ShortDescription { get; set; }

        public string ImagePath { get; set; }

        [Required(ErrorMessage = "Bắt buộc nhập trường này")]
        public string Content { get; set; }

        public DateTime CreateDate { get; set; } = DateTime.Now;

        public Boolean Visible { get; set; }

        [ForeignKey("IdentityUser")]
        public string UserId { get; set; }

        public virtual IdentityUser IdentityUser { get; set; }

    }
}

EstateInvestmentWebApplication/Controllers/ConsultationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EstateInvestmentWebApplication.Data;
using EstateInvestmentWebApplication.Models.DatabaseEntitiesModel;
using Microsoft.AspNetCore.Mvc;
using ReflectionIT.Mvc.Paging;

namespace EstateInvestmentWebApplication.Controllers
{
    public class ConsultationController : Controller
    {
        ApplicationDbContext _dbContext;
        public ConsultationController(ApplicationDbContext db)
        {
            _dbContext = db;
        }

        [HttpPost]
        public JsonResult CreateConsultation(Consultation model)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Consultations.Add(model);
                _dbContext.SaveChanges();

                return Json(new { status = "success", message = "Thông điệp của bạn đã được chuyển đi thành công. Xin cảm ơn." });
            }

            return Json(new { status = "fail", message = "Thông tin không đủ hoặc không hợp lệ" });
        }


        [HttpGet]
        [Route("admin/thong-tin-tu-van/{page?}")]
        public async Task<IActionResult> ListConsultation(int page = 1)
        {
            var listConsultation = _dbContext.Consultations.OrderByDescending(x => x.CreateDate);

            var model = await PagingList.CreateAsync(listConsultation,10,page);
            return View(model);
        }

        [HttpPost]
        public IActionResult DeleteConsultation([FromForm]int id)
        {
            var consultation = _dbContext.Consultations.Find(id);
            _dbContext.Remove(consultation);
            _dbContext.SaveChanges();

            return RedirectToAction("ListConsultation");
        }
            
    }

}

EstateInvestmentWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EstateInvestmentWebApplication.Models;
using EstateInvestmentWebApplication.Data;
using EstateInvestmentWebApplication.Models.DatabaseEntitiesModel;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;

namespace EstateInvestmentWebApplication.Controllers
{
    public class HomeController : Controller
    {
        ApplicationDbContext _dbContext;

        public HomeController(ApplicationDbContext db) 
        {
            _dbContext = db;
        }
        
        //[Route("trang-chu")]
        public async Task<IActionResult> Index(int id = 0,int page = 1)
        {
            IOrderedQueryable<EstateProject> listEstate;
            List<New> listNew;
            listNew = _dbContext.News.Where(x => x.Visible == true).OrderByDescending(x => x.CreateDate).Take(3).ToList();
            ViewBag.listNew = listNew;

            //Load Estate Project by catalog
            if (id != 0)
            {
                listEstate = _dbContext.EstateProjects.Where(x => x.Visible == true).Where(x => x.CatalogId == id).OrderByDescending(x => x.CreateDate);
            }
            //Default is all Estate Project of catalog
            else
            {
                listEstate = _dbContext.EstateProjects.Where(x => x.Visible == true).OrderByDescending(x => x.CreateDate);
            }

            var model = await PagingList.CreateAsync(listEstate, 6, page);

            return View(model);
        }

        [Route("gioi-thieu")]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        [Route("lien-he")]
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        [Route("tin-tuc")]
        public async Task<IActionResult> News(int page = 1)
        {
            IOrderedQueryable<New> listNew;

            listNew = _dbContext.News.Where(x => x.Visible == true).OrderByDescending(x => x.CreateDate);
            var model = await PagingList.CreateAsync(listNew, 6, page);

            return View(model);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EstateInvestmentWebApplication/Controllers/NewController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EstateInvestmentWebApplication.Data;
using EstateInvestmentWebApplication.Models.DatabaseEntitiesModel;
using EstateInvestmentWebApplication.Models.ViewModels;
using EstateInvestmentWebApplication.Services;
using HtmlAgilityPack;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;

namespace EstateInvestmentWebApplication.Controllers
{
    public class NewController : Controller
    {

        ApplicationDbContext _dbContext;
        IHostingEnvironment _hostingEnvironment;
        UserManager<IdentityUser> _userManager;
        RoleManager<IdentityRole> _roleManager;

        public NewController(IHostingEnvironment he, ApplicationDbContext db, UserManager<IdentityUser> um, RoleManager<IdentityRole> rm)
        {
            _dbContext = db;
            _hostingEnvironment = he;
            _userManager = um;
            _roleManager = rm;
        }

        [HttpGet]
        [Route("admin/tin-tuc/tao-tin-tuc")]
        public IActionResult CreateNew()
        {
            return View();
        }

        [HttpPost]
        [Route("admin/tin-tuc/tao-tin-tuc")]
        public IActionResult CreateNew(CreateNewViewModel model)
        {
            if (ModelState.IsValid)
            {
                New news = new New();

                //Upload Thumbnail File Image
                EstateProjectController estateProjectController = new EstateProjectController(_hostingEnvironment,_dbContext,_userManager,_roleManager);
                var imageUploadResult = estateProjectController.UploadImage(model.Image, "thumbnails");
                string imagePath = imageUploadResult.Value.GetType().GetProperty("url").GetValue(imageUploadResult.Value, null).ToString();

                news.ImagePath = imagePath;
                news.Title = model.Title;
                news.ShortDescription = model.ShortDescription;
                news.Content = model.Content;
                news.UserId = _userManager.GetUserId(User);
                news.Visible = true;

                _dbContext.News.Add(news);
                _dbContext.SaveChanges();
                
                return RedirectToAction("ListNew");
            }

            return View(model);
        }


        [HttpGet]
        [Route("admin/tin-tuc/chinh-sua/{id}")]
        public IActionResult EditNew(int id)
        {
            var news = _dbContext.News.Find(id);

            CreateNewViewModel createModel = new CreateNewViewModel();
            createModel.Id = news.Id;
            createModel.Content = news.Content;
            createModel.CreateDate = news.CreateDate;
            createModel.ShortDescription = news.ShortDescription;
            createModel.Title = news.Title;
            createModel.ImagePath = news.ImagePath;

            return View(createModel);
        }



        [HttpPost]
        [Route("admin/tin-tuc/chinh-sua/{id}")]
        public IActionResult EditNew(CreateNewViewModel model)
        {
            if (model.Image == null)
            {
                ModelState["Image"].ValidationState = Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Valid;
            }

            if (ModelState.IsValid)
            {
                var news = _dbContext.News.Find(model.Id);
                news.Title = model.Title;
                news.ShortDescription = model.ShortDescription;
                news.Content = model.Content;
                if (model.Image != null)
                {
                    //Delete Old Thumbnail File Image
                    var filePathArr = news.ImagePath.Split('/');
                    string fileName = filePathArr[filePathArr.Length - 1];
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), _hostingEnvironment.WebRootPath, "images", "thumbnails", fileName);
                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }

                    //Upload New Thumbnail File Image
                    EstateProjectController estateProjectController = new EstateProjectController(_hostingEnvironment, _dbContext, _userManager, _roleManager);
                    var imageUploadResult = estateProjectController.UploadImage(model.Image, "thumbnails");
                    string imagePath = imageUploadResult.Value.GetType().GetProperty("url").GetValue(imageUploadResult.Value, null).ToString();
                    news.ImagePath = imagePath;

                }
                _dbContext.Entry(news).State = EntityState.Modified;
                _dbContext.SaveChanges();

                return RedirectToAction("ListNew");
            }

            return View(model);
        }

        [HttpGet]
        [Route("tin-tuc/{id}")]
        public IActionResult DetailNew(int id)
        {
            var news = _dbContext.News.Find(id);

            return View(news);
        }

        [HttpGet]
        [Route("admin/tin-tuc/{page?}")]
        public async Task<IActionResult> ListNew(int page = 1)
        {
            var listNews = _dbContext.News.OrderByDescending(x => x.CreateDate);
            var model = await PagingList.CreateAsync(listNews, 10, page);

            return View(model);
        }

        [HttpPost]
        [Route("admin/tin-tuc/doi-trang-thai")]
        public void ChangeVisible([FromForm]int id, [FromForm]bool value)
        {
            var news = _dbContext.News.Find(id);
            news.Visible = value;
            _dbContext.Entry(news).State = EntityState.Modified;
            _dbContext.SaveChanges();
        }


        [HttpPost]
        [Route("admin/tin-tuc/xoa-tin-tuc")]
        public IActionResult DeleteNew([FromForm]int id)
        {
            var news = _dbContext.News.Find(id);

            //Read HTML content Find Img tag and get attribute src to delete image
            HtmlDocument doc = new HtmlDocument();
            byte[] byteArray = Encoding.ASCII.GetBytes(news.Content);
            MemoryStream stream = new MemoryStream(byteArray);
            doc.Load(stream);
            stream.Dispose();

            var lstTagImg = doc.DocumentNode.SelectNodes("/p/img");

            if (lstTagImg != null)
            {
                //Delete Image Content
                foreach (var tag in lstTagImg)
                {
                    var imgSrc = tag.Attributes["src"];
                    string[] arrPathImg = imgSrc.Value.Split('/');
                    string fileNameImg = arrPathImg[arrPathImg.Length - 1];
                    string filePathImg = Path.Combine(Directory.GetCurrentDirectory(), _hostingEnvironment.WebRootPath, "images", "imagescontent", fileNameImg);
                    if (System.IO.File.Exists(filePathImg))
                    {
                        System.IO.File.Delete(filePathImg);
                    }
                }
            }


            //Delete Image Thumnails
            string[] arrPath = news.ImagePath.Split('/');
            string fileName = arrPath[arrPath.Length - 1];
            string filePath = Path.Combine(Directory.GetCurrentDirectory(), _hostingEnvironment.WebRootPath, "images", "thumbnails", fileName);
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }

            _dbContext.News.Remove(news);
            _dbContext.SaveChanges();
            return RedirectToAction("ListNew");
        }

    }
}

EstateInvestmentWebApplication/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Giới thiệu";
}

<div class="site-blocks-cover inner-page-cover overlay" style="background-image: url(../images/hero_bg_2.jpg);" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center">
            <div class="col-md-10">
                <h1 class="mb-2">Giới thiệu</h1>
                <div><a href="@Url.Action("Index", "Home")">Trang chủ</a> <span class="mx-2 text-white">&bullet;</span> <strong class="text-white">Giới thiệu</strong></div>
            </div>
        </div>
    </div>
</div>

<div class="site-section border-bottom">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6" data-aos="fade-up" data-aos-delay="100">
                <img src="~/images/about.jpg" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-5 ml-auto" data-aos="fade-up" data-aos-delay="200">
                <div class="site-section-title mb-3">
                    <h2>Our Company</h2>
                </div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus in cum odio.</p>
                <p>Illum repudiandae ratione facere explicabo. Consequatur dolor optio iusto, quos autem voluptate ea? Sunt laudantium fugiat, mollitia voluptate? Modi blanditiis veniam nesciunt architecto odit voluptatum tempore impedit magnam itaque natus!</p>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 order-md-2" data-aos="fade-up" data-aos-delay="100">
                <img src="~/images/hero_bg_4.jpg" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-5 mr-auto order-md-1" data-aos="fade-up" data-aos-delay="200">
                <div class="site-section-title mb-3">
                    <h2>Our Office</h2>
                </div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus in cum odio.</p>
                <p>Illum repudiandae ratione facere explicabo. Consequatur dolor optio iusto, quos autem voluptate ea? Sunt laudantium fugiat, mollitia voluptate? Modi blanditiis veniam nesciunt architecto odit voluptatum tempore impedit magnam itaque natus!</p>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-7">
                <div class="site-section-title text-center">
                    <h2>Khách hàng</h2>
                </div>
            </div>
        </div>
        <div class="row block-13">

            <div class="nonloop-block-13 owl-carousel">

                <div class="slide-item">
                    <div class="team-member text-center">
                        <img src="~/images/person_1.jpg" alt="Image" class="img-fluid mb-4 w-50 rounded-circle mx-auto">
                        <div class="text p-3">
                            <h2 class="mb-2 font-weight-light text-black h4">Megan Smith</h2>
                            <span class="d-block mb-3 text-white-opacity-05">Guest</span>
                            <p class="mb-5">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi dolorem totam non quis facere blanditiis praesentium est. &rdquo;</p>

                        </div>
                    </div>
                </div>

                <div class="slide-item">
                    <div class="team-member text-center">
                        <img src="~/images/person_2.jpg" alt="Image" class="img-fluid mb-4 w-50 rounded-circle mx-auto">
                        <div class="text p-3">
                            <h2 class="mb-2 font-weight-light text-black h4">Brooke Cagle</h2>
                            <span class="d-block mb-3 text-white-opacity-05">Guest</span>
                            <p class="mb-5">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi dolorem totam non quis facere blanditiis praesentium est. &rdquo;</p>

                        </div>
                    </div>
                </div>

                <div class="slide-item">
                    <div class="team-member text-center">
                        <img src="~/images/person_3.jpg" alt="Image" class="img-fluid mb-4 w-50 rounded-circle mx-auto">
                        <div class="text p-3">
                            <h2 class="mb-2 font-weight-light text-black h4">Philip Martin</h2>
                            <span class="d-block mb-3 text-white-opacity-05">Guest</span>
                            <p class="mb-5">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi dolorem totam non quis facere blanditiis praesentium est. &rdquo;</p>

                        </div>
                    </div>
                </div>

                <div class="slide-item">
                    <div class="team-member text-center">
                        <img src="~/images/person_1.jpg" alt="Image" class="img-fluid mb-4 w-50 rounded-circle mx-auto">
                        <div class="text p-3">
                            <h2 class="mb-2 font-weight-light text-black h4">Megan Smith</h2>
                            <span class="d-block mb-3 text-white-opacity-05">Guest</span>
                            <p class="mb-5">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi dolorem totam non quis facere blanditiis praesentium est. &rdquo;</p>

                        </div>
                    </div>
                </div>

                <div class="slide-item">
                    <div class="team-member text-center">
                        <img src="~/images/person_2.jpg" alt="Image" class="img-fluid mb-4 w-50 rounded-circle mx-auto">
                        <div class="text p-3">
                            <h2 class="mb-2 font-weight-light text-black h4">Brooke Cagle</h2>
                            <span class="d-block mb-3 text-white-opacity-05">Guest</span>
                            <p class="mb-5">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi dolorem totam non quis facere blanditiis praesentium est. &rdquo;</p>

                        </div>
                    </div>
                </div>

                <div class="slide-item">
                    <div class="team-member text-center">
                        <img src="~/images/person_3.jpg" alt="Image" class="img-fluid mb-4 w-50 rounded-circle mx-auto">
                        <div class="text p-3">
                            <h2 class="mb-2 font-weight-light text-black h4">Philip Martin</h2>
                            <span class="d-block mb-3 text-white-opacity-05">Guest</span>
                            <p class="mb-5">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi dolorem totam non quis facere blanditiis praesentium est. &rdquo;</p>

                        </div>
                    </div>
                </div>

                <div class="slide-item">
                    <div class="team-member text-center">
                        <img src="~/images/person_1.jpg" alt="Image" class="img-fluid mb-4 w-50 rounded-circle mx-auto">
                        <div class="text p-3">
                            <h2 class="mb-2 font-weight-light text-black h4">Megan Smith</h2>
                            <span class="d-block mb-3 text-white-opacity-05">Guest</span>
                            <p class="mb-5">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi dolorem totam non quis facere blanditiis praesentium est. &rdquo;</p>

                        </div>
                    </div>
                </div>

                <div class="slide-item">
                    <div class="team-member text-center">
                        <img src="~/images/person_2.jpg" alt="Image" class="img-fluid mb-4 w-50 rounded-circle mx-auto">
                        <div class="text p-3">
                            <h2 class="mb-2 font-weight-light text-black h4">Brooke Cagle</h2>
                            <span class="d-block mb-3 text-white-opacity-05">Guest</span>
                            <p class="mb-5">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi dolorem totam non quis facere blanditiis praesentium est. &rdquo;</p>

                        </div>
                    </div>
                </div>

                <div class="slide-item">
                    <div class="team-member text-center">
                        <img src="~/images/person_3.jpg" alt="Image" class="img-fluid mb-4 w-50 rounded-circle mx-auto">
                        <div class="text p-3">
                            <h2 class="mb-2 font-weight-light text-black h4">Philip Martin</h2>
                            <span class="d-block mb-3 text-white-opacity-05">Guest</span>
                            <p class="mb-5">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi dolorem totam non quis facere blanditiis praesentium est. &rdquo;</p>

                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

EstateInvestmentWebApplication/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Liên hệ";
}

<div class="site-blocks-cover inner-page-cover overlay" style="background-image: url(../images/hero_bg_2.jpg);" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center">
            <div class="col-md-10">
                <h1 class="mb-2">Thông tin liên hệ</h1>
                <div><a href="@Url.Action("Index", "Home")">Trang chủ</a> <span class="mx-2 text-white">&bullet;</span> <strong class="text-white">Liên hệ</strong></div>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row">

            <div class="col-md-12 col-lg-8 mb-5">



                <form id="formConsultationContact" class="p-5 bg-white border">

                    <div class="row form-group required-field">
                        <div class="col-md-12 mb-3 mb-md-0">
                            <label class="font-weight-bold" for="fullname">Họ và tên:</label>
                            <input type="text" id="UserNameConsultationContact" name="UserName" class="form-control" placeholder="Mời nhập họ và tên">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <label class="font-weight-bold" for="email">Địa chỉ email:</label>
                            <input type="email" id="UserEmailConsultationContact" name="UserEmail" class="form-control" placeholder="Mời nhập địa chỉ email">
                        </div>
                    </div>
                    <div class="row form-group required-field"">
                        <div class="col-md-12">
                            <label class="font-weight-bold" for="phone">Số điện thoại:</label>
                            <input type="text" id="PhoneNumberConsultationContact" name="PhoneNumber" class="form-control" placeholder="Mời nhập số điện thoại">
                        </div>
                    </div>


                    <div class="row form-group required-field"">
                        <div class="col-md-12">
                            <label class="font-weight-bold" for="message">Thông tin cần tư vấn:</label>
                            <textarea id="ContentConsultationContact" name="Content" cols="30" rows="5" class="form-control" placeholder="Mời nhập thông tin cần tư vấn"></textarea>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-md-12">
                            <input id="btnSubmitConsultationContact" type="submit" value="Gửi thông tin" class="btn btn-primary py-2 px-4">
                        </div>
                    </div>


                </form>
            </div>

            <div class="col-lg-4">
                <div class="p-4 mb-3 bg-white">
                    <h3 class="h6 text-black mb-3 text-uppercase">Thông tin liên hệ</h3>
                    <p class="mb-0 font-weight-bold">Địa chỉ</p>
                    <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

                    <p class="mb-0 font-weight-bold">Số điện thoại</p>
                    <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

                    <p class="mb-0 font-weight-bold">Địa chỉ email</p>
                    <p class="mb-0"><a href="#">youremail@domain.com</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
        //Begin Submit Consultation
        document.getElementById("formConsultationContact").addEventListener('submit', (e) => {
            const formData = new FormData(e.target);
            $("btnSubmitConsultationContact").prop('disabled', true);
            $.ajax({
                url: "@Url.Action("CreateConsultation","Consultation")",
                contentType: false,
                type: "post",
                processData: false,
                data: formData
            }).done(function (data) {
                $("btnSubmitConsultationContact").prop('disabled', false);

                if (data.status == "success") {
                    alert(data.message);
                    ClearFormConsultationContact();
                } else {
                    alert(data.message);

                }
            })

            e.preventDefault()
        });
</script>

EstateInvestmentWebApplication/Views/Home/News.cshtml
@using ReflectionIT.Mvc.Paging

@model PagingList<EstateInvestmentWebApplication.Models.DatabaseEntitiesModel.New>

@{
    ViewData["Title"] = "Tin tức";
}

<div class="site-section site-section-sm bg-light">
    <div class="container">

        <div class="row mb-5">

            @foreach (var news in Model)
            {

                <div class="col-md-6 col-lg-4 mb-5" data-aos="fade-up" data-aos-delay="300">
                    <a href="@Url.Action("DetailNew", "New", new { id = news.Id })"><img src="@news.ImagePath" alt="Image" class="img-fluid"></a>
                    <div class="p-4 bg-white">
                        <span class="d-block text-secondary small text-uppercase">@news.CreateDate</span>
                        <h2 class="h5 text-black mb-3"><a href="#">@news.Title</a></h2>
                        <p>@news.ShortDescription</p>
                    </div>
                </div>
            }

        </div>

        <div class="row">
            <div class="col-md-12 text-center">
                <div class="site-pagination">
                    <vc:pager paging-list="@Model" />
                </div>
            </div>
        </div>

    </div>
</div>