EstateInvestmentWebApplication/Controllers/NumberUserAccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EstateInvestmentWebApplication.Data;
using Microsoft.AspNetCore.Mvc;

namespace EstateInvestmentWebApplication.Controllers
{
    public class NumberUserAccessController : Controller
    {
        ApplicationDbContext _dbContext;
        public NumberUserAccessController(ApplicationDbContext db)
        {
            _dbContext = db;
        }

        [Route("admin/thong-ke-truy-cap")]
        [HttpGet]
        public IActionResult NumberUserAccessChart()
        {
            return View();
        }

        [Route("admin/lay-danh-sach-thong-ke")]
        [HttpGet]
        public JsonResult GetListNumberUserAccess()
        {
            List<string> day = new List<string>();
            List<int> numberUser = new List<int>();

            var listNumberUserAccesses = _dbContext.NumberUserAccesses.OrderByDescending(x => x.Date).Take(7);
            foreach(var item in listNumberUserAccesses)
            {
                day.Insert(0, item.Date.ToString("d"));
                numberUser.Insert(0, item.UserNumber);
            }

            return Json(new { day = day, numberUser = numberUser });
             
        }


    }


}

EstateInvestmentWebApplication/Views/NumberUserAccess/NumberUserAccessChart.cshtml
@{
    ViewData["Title"] = "NumberUserAccessChart";
}

<h2>Thống kê lượng user truy cập</h2>

<canvas id="myChart" style="max-width:900px;max-height:700px;"></canvas>


<script src="~/js/chartjs/chart.js/dist/Chart.js"></script>

<script>
    $.getJSON("@Url.Action("GetListNumberUserAccess","NumberUserAccess")",
        function (data) {
            new Chart(document.getElementById("myChart"), {
            "type": "line",
            "data": {
            "labels": data.day,
            "datasets": [{
                "label": "Số lượng người truy cập trong ngày",
                "data": data.numberUser,
                "fill": false, "borderColor": "rgb(75, 192, 192)",
                "lineTension": 0.1
            }]
            },
            "options": {
              tooltips: {
                callbacks: {
                  label: (item) => `${item.yLabel} Người`,
                },
              },
            }

            });
    });

    

</script>